### ISSUE TITLE
Ignoring Tags/Words

### ISSUE THREAD

**Issue by joethei** [joethei/obsidian-tagcloud#1]
Add an option to 

- Ignore Stopwords (https://en.m.wikipedia.org/wiki/Stop_word):
List for english here: https://gist.github.com/sebleier/554280

**Comment by jsmm** [comment]
It doesn't seem to take into account stopwords. Could it be because my word list includes foreign words with special characters, such as `áéíóúüñ`?

**Comment by joethei** [comment]
Which language are you writing in?
Or did you create your own list in the settings?

**Comment by jsmm** [comment]
I created my own list, in Spanish. Here are some sample words:

```
algún
así
atrás
cómo
entré
año
lingüística
```
