### ISSUE TITLE
Feature request: Queries for word cloud

### ISSUE THREAD

**Issue by masonroyal** [joethei/obsidian-tagcloud#10]
The main reason I want to use this plugin is for word clouds. I want to analyze my morning pages for a particular month and see what was on my mind that month.

Would it be possible to add queries to word clouds so I can generate a word cloud for a certain group of files instead of just my entire vault or the individual file?

**Comment by chrsdk** [comment]
Is this solved? What kind of query would limit the tag cloud to display only the tags for a certain month?
