### ISSUE TITLE
Only seeing stopwords, nothing else.

### ISSUE THREAD

**Issue by catsynth** [joethei/obsidian-tagcloud#11]
I recently installed the plug-in, had it scan my notes, and created a note with this code:
`
```wordcloud
stopwords: false
```
`
Right now, I only see stopwords (e.g., "the", "and", etc.), no other words.

![Screen Shot 2022-11-29 at 10 28 45 AM](https://user-images.githubusercontent.com/8483574/204615444-71ec12d9-c1e0-4da3-81f8-a2129635ecd0.png)

Any ideas?  (I'm hoping it's just user error on my part ;) )

**Comment by jaredpinargote** [comment]
I am also seeing this exact behavior as well

**Comment by elephino** [comment]
Try adding a maxDepth attribute w/ a sufficiently large value to see more words. Unfortunately stopwords may still show up in your output because it's not entirely clear if that functionality is working properly at the moment.

**Comment by mrprints** [comment]
Going to test this fix out asap! Thank you!!
