### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by joleaf** [joethei/obsidian-tagcloud#15]
Hey, I really like the tagcloud plugin!

Unfortunately, I want to remove some words inside the cloud which are not stopwords.
E.g. I want to select all tags from a query with the tag '#article' and I don't want the word "article" in the result.
````
```tagcloud
source: query
query: '#article' 
exclude:
  - article
  - ...
```
````
Is something similar possible? If not, are PRs possible?

**Comment by SeveNOlogy7** [comment]
Hey @joleaf, I agree with you, I'm in need of similar feature as well. It would be great to have the ability to remove certain words from the tag cloud.

**Comment by joethei** [comment]
I've released a new version which includes this feature (thanks @SeveNOlogy7 for the PR)
Additionally, you can configure excluded tags for all tag clouds from the plugin settings.
