### ISSUE TITLE
stopwords not working

### ISSUE THREAD

**Issue by fabionolasco** [joethei/obsidian-tagcloud#5]
Hi there,

First, thank you for the plugin! Super cool!

I am using version 1.3.1 with Obsidian version 0.13.23

I added one word per line on the stopwords field on the options part of the TagCloud plugin, like so:
the
a
on
in
that
is
to
for
do
our
will
would
should
could
from
and
if
this
these
those
with
as
may
therefore
but
are
there
if

**I also tried to force it by adding the stopword: true**

````
  ```wordcloud
  source: file
  stopwords: true
  ```
  
  and
  
  ```wordcloud
  source: file
  ```
````

The tag cloud shows up, but the stopwords also show up.

I already tried to close and reopen Obsidian.
I already tried to delete the text and re-add it.

Any ideas what could be wrong?

Thank you!

**Comment by joethei** [comment]
Version 1.3.2 has fixed an issue where custom stopwords would not be applied.
Please keep in mind that you will need to recalculate the word distribution everytime you change anything in the settings and after updating to that version.
There is a command as well as a button in the settings.
(The frequency analysis can take a long time, so not automatic.)

**Comment by kauffy** [comment]
@joethei I'm using 1.3.2, and not only are the stopwords not used, the word cloud seems to be almost _only_ the stopwords!
It also seems that changing any of the options has no effect on the word cloud (it's too small, and it doesn't change from generation to generation)-- the other clouds (tag, link) seem to respond as expected, but the word cloud seems to be deterministically wrong. I have had it recalculate the word distribution a bunch of times, but same result.

```
wordcloud
stopwords = true
width = 800
height = 600
maxDepth = 50

```
Stop words:
![image](https://user-images.githubusercontent.com/2880436/163686778-cb4abad9-fa10-48c5-a26a-bf5c2254ba29.png)

Yields:
![image](https://user-images.githubusercontent.com/2880436/163686551-e07cc7c2-5b3d-4e9b-9db4-59398b157534.png)

Recalculating word distribution, then:

![image](https://user-images.githubusercontent.com/2880436/163686631-1897d9a4-1771-4030-a4d7-26d902c44397.png)

**Comment by berot3** [comment]
Hey, I also wanted to report that it doesn't remove stop words for me (v1.3.2)

I tried 

```
	```wordcloud
	source: file
	```
```

and 

```
	```wordcloud
	source: file
	stopwords: true
	```
```

produces:

![image](https://user-images.githubusercontent.com/52616/173780860-adb0f8ad-c4f2-4bb9-8e7a-bab82b4e594c.png)

**Comment by berot3** [comment]
So sorry, after copy/pasting this: https://github.com/igorbrigadir/stopwords/blob/master/en/terrier.txt
into the plaugin-settings it works like a charm. I somehow assumed that they were already added by default. oops!

**Comment by tekiegirl** [comment]
Loving this plugin, except that I have this stopword problem too, using v 1.3.2 of this plugin with Obsidian 0.14.15

I have 

- added the same list as berot3, above
- recalculated word distribution
- restarted Obsidian
- added `stopwords: true` to try to force it

Many thanks for your work on this.

**Comment by leodking** [comment]
Hi, I wanted to report I'm having the same issues as the others. Love the idea of this plugin, but unfortunately it only shows me stopwords right now, despite defining these in the custom list. I've recalculated the vault several times.

![image](https://user-images.githubusercontent.com/72651324/182697904-7df1ce93-0c16-497a-8028-8625fb22df12.png)

**Comment by tekiegirl** [comment]
This is still an issue for me. Not sure if it has been fixed since the last release, but I know that my bug fix for another issue has not been released yet (as of Oct 21 '22) as I have to manually apply it to the code in my vault 😉
If I have time I will try to debug this one too.

**Comment by joethei** [comment]
yeah, It's still an issue, I am not always fast enough to stop the bot from closing the issue.

**Comment by irasanchez** [comment]
@joethei did you want some help on this? I know it's been a while, so no pressure if you've moved on and are over it. It's just the only plugin that really provides a feature like this. If you'd prefer that I fork and tinker on my own, that's fine too. Whenever you have some time, let me know your preferences.

Thanks for making this!
